version: '3.8'

services:
  db:
    image: mysql:5.7.41
    environment:
      MYSQL_DATABASE: biblio_db
      MYSQL_ROOT_PASSWORD: Enrico.DB
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app
    depends_on:
      - db
  
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  mysql-data: